In [30]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [31]:
df = load_iris()

In [32]:
dir(df)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [33]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [34]:
lr = cross_val_score(LogisticRegression(max_iter=1000), df.data, df.target)
lr

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [35]:
lr_final = np.average(lr)
lr_final

0.9733333333333334

In [36]:
svc = cross_val_score(SVC(),df.data,df.target)
svc

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [37]:
svc_final = np.average(svc)
svc_final

0.9666666666666666

In [38]:
dt = cross_val_score(DecisionTreeClassifier(), df.data, df.target)
dt

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [39]:
dt_final = np.average(dt)
dt_final

0.9600000000000002

In [29]:
rfc = cross_val_score(RandomForestClassifier(n_estimators=25), df.data, df.target)
rfc

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [24]:
rfc_final = np.average(rfc)
rfc_final

0.9666666666666668